### ISSUE TITLE
Добавить дополнительные поля для пользователей и групп пользователей

### ISSUE THREAD

**Issue by Kr00t** [YaponchikLIN/trudesk#3]
Добавить дополнительные поля:
для групп пользователей
- Телефон
- Сайт
- Адрес

для пользователей:

- Телефон

**Comment by YaponchikLIN** [comment]
Завершено.
Выполненные задачи:
Добавить дополнительные поля:
для групп пользователей

- Телефон
- Сайт
- Адрес

для пользователей:

- Телефон
