### ISSUE TITLE
Добавить интеграцию с ChatWoot

### ISSUE THREAD

**Issue by Kr00t** [YaponchikLIN/trudesk#6]
В случае перехода в ChatWoot На закладку trudesk (в chatwoot это называется приложения) необходимо обработать переход на trudesk по следующему алгоритму:
Аннотация:
- Поиск осуществляется по номеру телефона в формате +X. - т.е. начиная с плюса все цифры номера, так как номер может быть не российский.
- Формат дополнительного поля trudesk string, думаю туда стоит писать номер заявки и по нему уже искать в алгоритме ниже
-  

Алгоритм:

1. Если поиск пользователя по номеру не дал результата, открывается форма выбора создания пользователя или привязка:
а. создания пользователя с заполненными полями chatwoot - trudesk:
- Full Name - Name
- Email Address - Email
- Phone - Phone Number
- Role = User
- Groups = определяется по почте пользователя, если не определено значит пусто.
б. если происходит привязка пользователя, то подставляется только номер телефона в карточку и через API прописывается email в chatwoot. Не забываем, что у пользователей trudesk свои API KEY Для chatwoot

3. Если пользователь найден и в chatwoot отсутствует дополнительное поле trudesk (поле кастомное и может называться с большой или маленькой буквы, но обязательно trudesk https://disk.yandex.ru/i/adEbr6TBJ8d2cw), тогда открывается список всех заявок найденного пользователя
4. Если пользователь найден в chatwoot и присутствует дополнительное поле с заполненной заявкой - открывать ее.

Дополнительно:
- при сохранении заявки в trudesk сохранять номер заявки в дополнительное поле в chatwoot, думаю стоит добавить настройки chatwoot в trudesk у пользователя, чтобы можно было там указать API KEY

**Comment by YaponchikLIN** [comment]
Завершено.
Выполненные задачи:
В случае перехода в ChatWoot На закладку trudesk (в chatwoot это называется приложения) необходимо обработать переход на trudesk по следующему алгоритму:
Аннотация:

- Поиск осуществляется по номеру телефона в формате +X. - т.е. начиная с плюса все цифры номера, так как номер может быть не российский.
- Формат дополнительного поля trudesk string, думаю туда стоит писать номер заявки и по нему уже искать в алгоритме ниже

Алгоритм:

1. Если поиск пользователя по номеру не дал результата, открывается форма выбора создания пользователя или привязка:
а. создания пользователя с заполненными полями chatwoot - trudesk:

- Full Name - Name
- Email Address - Email
- Phone - Phone Number
- Role = User
- Groups = определяется по почте пользователя, если не определено значит пусто.

б. если происходит привязка пользователя, то подставляется только номер телефона в карточку и через API прописывается email в chatwoot. Не забываем, что у пользователей trudesk свои API KEY Для chatwoot
2. Если пользователь найден и в chatwoot отсутствует дополнительное поле trudesk (поле кастомное и может называться с большой или маленькой буквы, но обязательно trudesk https://disk.yandex.ru/i/adEbr6TBJ8d2cw), тогда открывается список всех заявок найденного пользователя
3. Если пользователь найден в chatwoot и присутствует дополнительное поле с заполненной заявкой - открывать ее.
Дополнительно:

- при сохранении заявки в trudesk сохранять номер заявки в дополнительное поле в chatwoot, думаю стоит добавить настройки chatwoot в trudesk у пользователя, чтобы можно было там указать API KEY
