### ISSUE TITLE
Ряд недоработок, исправить

### ISSUE THREAD

**Issue by Kr00t** [YaponchikLIN/trudesk#7]
1. При отключении LDAP после первой установки и нажатии кнопки APPLY https://disk.yandex.ru/i/A1JQnxr1xIXaeA перекидывает на неведомую страницу https://trudesk-dev.shatura.pro/settings/accounts
2. По умолчанию при первой установке установки LDAP и Chatwoot должны быть отключены
3. Это subject или ссылка я не пойму. Прояснить детальнее https://disk.yandex.ru/i/7_CRerSTqxHFtw добавить {ticket.uid} - номер заявки
4. Криво, нет смысла убрать совсем https://disk.yandex.ru/i/CN6wJW_dzQXhNA
5. При новой установке отсутствуют шаблоны https://disk.yandex.ru/i/s1ELsINglxIHCw
6. Чо за хрень? Уже вроде с пользователями проходили https://disk.yandex.ru/i/Tjs92o-yqFwgPA
7. В чем разница? https://disk.yandex.ru/i/iBY8gavB1y8q-w
8. Не забыть позакрывать уже отработанные issue тут.

**Comment by Kr00t** [comment]
1. При получении сообщения в систему, система генерит тонну уведомлений https://disk.yandex.ru/i/W-imze1O1UqwIQ при этом последнее уведомление без пароля https://disk.yandex.ru/i/22e9d8xXkLIGWA
2. Пользователь создается не верно, логин не содержит домена, а имя пользователя не берется из имени пользователя в почте https://disk.yandex.ru/i/_55F1aHPGs7y6A
3. При отправки сообщения с аттачем , сообщение игнорируется. Более того система не принимает сообщения с наименованием аттача на русском языке.
4. При ответе на сообщение - в заявку не попадаю комментарии. 
5. Поиск номера заявки необходимо искать по теме письма и ни как не по тексту.
6. При добавлении комментария в заявку с фото, уведомление не приходит.
7. Не работают аттачи файлов через web интерфейс формата docx, xlsx, doc, xls, zip, rar, gz, txt, pdf
8. LDAP не работает https://disk.yandex.ru/i/IyYao1nrjcnonw 
Логин CN=Ldap User,CN=Users,DC=shatura,DC=pro
Пароль v7XPP9F4,LPB
ldapuser
9. При сбросе пароля приходит типовой шаблон, нужно добавить в общий список шаблонов и отработать https://disk.yandex.ru/i/7JPfUGl1oP_8OA
10. При первом входе Агентов при создании подставлять данные из LDAP https://disk.yandex.ru/i/LFvPdqZIUQbuhw
11. Длина логина и имени короткая увеличить до 100 символов
12. При включении LDAP в определенном порядке не работает. Если включить сначала LDAP, потом заполнить данные, то с использованием check now - группы не отображаются
13. Наименование шаблонов всегда с большой буквы https://disk.yandex.ru/i/uuDBijaLUmo-dQ
14. При создании пользователя из chatwoot - запретить изменение роли на Admin или Support . В системе могут быть еще роли отличные от этих двух https://disk.yandex.ru/i/KGWNwMWPpAIMRQ
15. Размер поля не суразный https://disk.yandex.ru/i/DDW7-Y2wQk5nqg там же запретить редактировать поле Name , которое в свою очередь нужно переименовать в телефон (Phone). Более того если у пользователя не установлен chatwoot api key переход на форму нужно запретить ,чтобы избежать проблем с мапингом

**Comment by YaponchikLIN** [comment]
На текущий момент выполнено:
1. При получения сообщения генерируются только необходимые уведомления.
2. Пользователь через почту создаётся с именем из почты и username - сама почта
3. При отправки сообщения с аттачем всё работает корректно
4. При ответе на сообщение, если в шаблоне присутствует номер зявки с решёткой, то в эту заявку падает комментарий
5. Номер заявки ищется можно сказать в теме письма, так как при поиске берётся первый попавшийся номер с решёткой. А если искать по теме то при ответе на комментарий тема будет другая, там может и не быть номера
6. При добавлении комментария в заявку с фото и другими файлами уведомление приходит с аттачами на почту
7. Файлы аттачей работают, осталось проверить расширение .gz
8. LDAP работает
9. В общий списое шаблоново добавлен "Новый пароль". Для проверки нужно запустить в продакшене
10. При первом входе агентов представляются данные из ldap. С номером пока непонятно, нужно добавить номер телефона в ldap запись.
11. Длина логина и пароля увеличина до 100 символов
12. Испрвлен баг LDAP при включении настроек в определённом порядке
13. Наименования шаблонов исправлены
14. При создании пользователй из chatwoot запрещено изменение ролей на Admin или Support
15. Форма отредактирована, размер поля изменён, поле Phone нельзя поменять. Если у пользователя отсутствует chatwoot api key, то выводит ошибку

**Comment by Kr00t** [comment]
1. При отправки почты нужно подставлять имя отправителя это https://disk.yandex.ru/i/sRrwjKKRRYp3PA
2. При первом входе агента не подставляется https://disk.yandex.ru/i/_qRFNUrBLXStAg
3. При создании агента или пользователя пароль хранится открытым? https://disk.yandex.ru/i/EYw7Ssb7o4SK2w
4. При переходе на trudesk из chatwoot - trudesk падает

**Comment by YaponchikLIN** [comment]
1. При отправлении почты скорее всего подставляется имя, которое указано в ящике, так что нужно его менять там
2. При первом входе агента подставляется так же его title
3. При создании агента или пользователя пароль хранится зашифрованым
4. Надо проверить, у меня не падает

**Comment by Kr00t** [comment]
Ну по первому пункту это не так работает. Если используется email клиент, то имя пользователя задается клиентом а не веб интерфейсом, что очевидно.
