### ISSUE TITLE
Падает сервис 

### ISSUE THREAD

**Issue by Kr00t** [YaponchikLIN/trudesk#9]
1. Пытаемся войти через chatwoot в trudesk
2. Trudesk предлагает нам создать или замапить пользователя.
3. Создаем пользователя -после создания не запускается форма создания заявки!!!
4. Перезаходим в trudesk из chatwoot создаем заявку со следующими данными:

- Ставим галочку приаттачить диалог
- Добавляем в заявку аттач 
- Устанавливаем приоритет на Неотложный
После попытки запостить заявку она создается НО патает trudesk

**Comment by YaponchikLIN** [comment]
При создании заявки из chatwoot сервис не падает.
Добавленные изменения:
При добавлении комментария в заявку из trudesk и из почты выделяется строка в списке. При просмотре заявки выделение пропадает.
Решена проблема при получении сообщения с файлами.
При добавлении комментария в заявку приходит уведомление со звуком. Данное действие отображается в списке уведомлений.
